### ISSUE TITLE
stats are incorrect

### ISSUE THREAD

**Issue by max-mapper** [mafintosh/hypercore-archiver-bot#6]
I implemented `!status <key>` here: https://github.com/mafintosh/hypercore-archiver-bot/blob/c30ffac702cbce7225f55313c5f7d4d84d9910a0/index.js#L177-L194

I ran !status on a key I was importing three times over 10 minutes and got this output:

![screen shot 2016-12-19 at 2 14 54 pm](https://cloud.githubusercontent.com/assets/39759/21331227/1bd8d41a-c5f6-11e6-9d1c-b23521733cb8.png)

shouldn't 'need' be going down each time?

cc @mafintosh

**Comment by max-mapper** [comment]
also we should put file sizes in the output, saying 'need 14' is kinda confusing on its own

```
Status bf37b184c981c3db293f20530cd6461e39f8147c221b1e3ee03e08ef2b747547: need 14, have 14, %100
```

**Comment by joehand** [comment]
Fixed in new version.
