### ISSUE TITLE
make the bot announce

### ISSUE THREAD

**Issue by max-mapper** [mafintosh/hypercore-archiver-bot#7]
it should work like a normal dat peer by default, rather than the current mode where it only listens for the uploader to announce

this issue would make it possible to download *from* the bot which is important for lot of our use cases right now

**Comment by joehand** [comment]
We can use [archiver-server](https://github.com/joehand/archiver-server) for this. But we'd probably want to make it optional. Previous PR discussion: https://github.com/mafintosh/hypercore-archiver-bot/pull/2

**Comment by joehand** [comment]
fixed in new version
